# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3614a7dabe8d3508b6dae577bb163d2abb407c5ff7afbf9ba11564cab5efae5d9e9efd48a1e197cd906a477213b2afef276be579c92c2cdb38ac2f038791bb3b

test:
  secret_key_base: 977690dbdd31533c5921db4a04cbceb14b09368fa4b269090161d1f33e2b7a05ffe9f78b0f9639dedd4ef0342f1da31c15a1ee73caefb0d6dabffbaa859127e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
